name: udevs_todo
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-300.0.dev <4.0.0'

# consider running `flutter pub upgrade --major-versions`. Alternatively,

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  fluttertoast: ^8.2.1
  flutter_slidable: ^2.0.0

  # database (cache)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.20

  # state managment
  formz: ^0.4.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # service
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # generator
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/categories/
    - assets/lotties/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900

